//! Asynchronous settlement of an MVM deferred obligation by the PVM verifier.

use std::sync::Arc;

use miden_assembly::{Assembler, Linkage};
use miden_core::{
    Felt, Word,
    deferred::{PrecompileWitness, fold_deferred_root},
    events::{EventId, EventName},
    program::{ExecutionClaim, proof_request_key},
    proof::{ExecutionProof, HashFunction, PrecompileProof, PrecompileStatus},
};
use miden_core_lib::{CoreLibrary, PVM_PROOF_REQUEST_EVENT_NAME};
use miden_debug_types::{Location, SourceFile, SourceSpan};
use miden_precompiles_verifier::masm_verifier::{
    PvmRecursiveVerifierInputs, PvmRecursiveVerifierInputsError,
};
use miden_processor::{
    BaseHost, DefaultHost, ExecutionOptions, ExecutionOutput, FastProcessor, FutureMaybeSend, Host,
    LoadedMastForest, ProcessorState, StackInputs, SyncHost,
    advice::{AdviceInputs, AdviceMutation, AdviceStack},
    event::EventError,
};
use miden_prover::{Prover, ProverError};
use miden_verifier::{Verifier, recursive::RecursiveVerifierInputs};

use crate::{
    helpers::masm_push_word,
    support::ecdsa::{EcdsaFixture, valid_fixture},
};

mod batch;

#[tokio::test(flavor = "current_thread")]
async fn ecdsa_deferred_obligation_is_settled_end_to_end() {
    let core_lib = CoreLibrary::default();
    let (deferred_proof, claim, precompile_witness) =
        prove_ecdsa_execution(&core_lib, valid_fixture(), StackInputs::default());
    let outcome = Verifier::new()
        .verify(&claim, &deferred_proof)
        .expect("the MVM proof must authenticate its deferred obligation");
    let deferred_root = outcome
        .outstanding_precompile_root()
        .expect("the ECDSA execution must retain a deferred obligation");

    let settlement = run_settlement_in_masm(&core_lib, &deferred_proof, &claim, precompile_witness)
        .await
        .expect("failed to settle the deferred root");
    assert_eq!(
        settlement.precompile_proof.roots,
        [deferred_root],
        "the PVM proof must cover the MVM verifier's deferred root",
    );
    assert_eq!(
        settlement.output.stack.get_num_elements(4),
        vec![Felt::ZERO; 4],
        "settlement must consume the deferred root rather than return it",
    );

    let final_proof = deferred_proof
        .complete(settlement.precompile_proof)
        .expect("a deferred execution proof must accept its precompile proof");
    let outcome = Verifier::new()
        .verify(&claim, &final_proof)
        .expect("native final verification must accept the proof generated by the event");
    assert!(outcome.is_complete(), "the PVM proof must discharge the obligation");
}

/// Proves an ECDSA execution and returns its portable precompile witness for the PVM prover.
fn prove_ecdsa_execution(
    core_lib: &CoreLibrary,
    fixture: EcdsaFixture,
    stack_inputs: StackInputs,
) -> (ExecutionProof, ExecutionClaim, PrecompileWitness) {
    let source = format!(
        "
        begin
            {}
            {}
            exec.::miden::core::crypto::dsa::ecdsa_k256_keccak::verify
        end
        ",
        masm_push_word(&fixture.message),
        masm_push_word(&fixture.public_key_commitment),
    );
    let program = Assembler::default()
        .with_package(core_lib.package(), Linkage::Dynamic)
        .expect("core library must link")
        .assemble_program("ecdsa_deferred_settlement", source)
        .expect("ECDSA settlement fixture must assemble")
        .unwrap_program();
    let mut host = DefaultHost::default()
        .with_library(core_lib)
        .expect("core library must load into the host");
    let mut advice_stack = AdviceStack::new();
    advice_stack.append_elements(fixture.advice);
    let witness = FastProcessor::new_with_options(
        stack_inputs,
        AdviceInputs::default().with_stack(advice_stack),
        ExecutionOptions::default(),
    )
    .expect("ECDSA advice must fit provider limits")
    .execute_for_proving_sync(&program, &mut host)
    .expect("ECDSA execution must produce a proving witness");
    let claim = witness.claim();
    // The core library's recursive verifiers accept Poseidon2 proofs.
    let proof = Prover::new()
        .with_hash_fn(HashFunction::Poseidon2)
        .prove(witness)
        .expect("ECDSA execution must produce a deferred MVM proof");
    let PrecompileStatus::Deferred(precompile) = proof.precompile() else {
        panic!("ECDSA execution must retain deferred precompile work")
    };
    let precompile_witness = precompile.clone();

    (proof, claim, precompile_witness)
}

struct SettlementResult {
    output: ExecutionOutput,
    precompile_proof: PrecompileProof,
}

async fn run_settlement_in_masm(
    core_lib: &CoreLibrary,
    deferred_proof: &ExecutionProof,
    claim: &ExecutionClaim,
    precompile_witness: PrecompileWitness,
) -> Result<SettlementResult, miden_processor::ExecutionError> {
    let vm = RecursiveVerifierInputs::for_request(
        core_lib.vm_recursive_verifier_root(),
        deferred_proof,
        claim,
    )
    .expect("partial MVM proof must adapt to recursive-verifier advice");
    let (advice_inputs, claim_commitment) = vm.into_parts();
    assert!(advice_inputs.stack().is_empty(), "the MVM proof stream must be map-backed");

    let stack_inputs = StackInputs::new(claim_commitment.as_elements())
        .expect("claim commitment must fit the stack");
    let program = assemble_settlement_program(core_lib);
    let mut host = PvmSettlementHost::new(core_lib, vec![precompile_witness]);

    let output =
        FastProcessor::new_with_options(stack_inputs, advice_inputs, ExecutionOptions::default())
            .expect("failed to construct FastProcessor")
            .execute(&program, &mut host)
            .await?;
    let precompile_proof = host
        .precompile_proof
        .take()
        .expect("successful settlement must retain the generated proof");

    Ok(SettlementResult { output, precompile_proof })
}

fn assemble_settlement_program(core_lib: &CoreLibrary) -> miden_processor::Program {
    let guide =
        include_str!("../../../../../docs/src/user_docs/core_lib/recursive_verification.md");
    let (_, example) = guide
        .split_once("```masm title=\"settle_deferred.masm\"\n")
        .expect("guide must contain the settlement example");
    let (source, _) = example.split_once("\n```").expect("settlement code block must be closed");

    Assembler::default()
        .with_package(core_lib.package(), Linkage::Dynamic)
        .expect("core library must link")
        .assemble_program("async_pvm_settlement", source)
        .expect("async settlement program must assemble")
        .unwrap_program()
}

/// Generates a PVM proof from its witness when `pvm::request_proof` emits an event.
struct PvmSettlementHost {
    inner: DefaultHost,
    event_name: EventName,
    expected_verifier_root: Word,
    precompile_witnesses: Vec<PrecompileWitness>,
    precompile_proof: Option<PrecompileProof>,
}

impl PvmSettlementHost {
    fn new(core_lib: &CoreLibrary, precompile_witnesses: Vec<PrecompileWitness>) -> Self {
        let inner = DefaultHost::default()
            .with_library(core_lib)
            .expect("core library must load into the settlement host");
        Self {
            inner,
            event_name: PVM_PROOF_REQUEST_EVENT_NAME,
            expected_verifier_root: core_lib.pvm_recursive_verifier_root(),
            precompile_witnesses,
            precompile_proof: None,
        }
    }
}

impl BaseHost for PvmSettlementHost {
    fn get_label_and_source_file(
        &self,
        location: &Location,
    ) -> (SourceSpan, Option<Arc<SourceFile>>) {
        BaseHost::get_label_and_source_file(&self.inner, location)
    }

    fn resolve_event(&self, event_id: EventId) -> Option<&EventName> {
        if event_id == PVM_PROOF_REQUEST_EVENT_NAME.to_event_id() {
            Some(&self.event_name)
        } else {
            BaseHost::resolve_event(&self.inner, event_id)
        }
    }
}

impl Host for PvmSettlementHost {
    fn get_mast_forest(
        &self,
        node_digest: &Word,
    ) -> impl FutureMaybeSend<Option<LoadedMastForest>> {
        let forest = SyncHost::get_mast_forest(&self.inner, node_digest);
        async move { forest }
    }

    fn on_event(
        &mut self,
        process: &ProcessorState<'_>,
    ) -> impl FutureMaybeSend<Result<Vec<AdviceMutation>, EventError>> {
        async move {
            let event_id = EventId::from_felt(process.get_stack_item(0));
            if event_id != PVM_PROOF_REQUEST_EVENT_NAME.to_event_id() {
                return SyncHost::on_event(&mut self.inner, process);
            }

            // The event stack is [event_id, verifier_root, deferred_root]. Each root is four
            // field elements, so the two roots start at positions 1 and 5.
            let verifier_root = process.get_stack_word(1);
            let requested_root = process.get_stack_word(5);
            if verifier_root != self.expected_verifier_root {
                return Err(SettlementEventError::VerifierRootMismatch {
                    requested: verifier_root,
                    expected: self.expected_verifier_root,
                }
                .into());
            }
            let available_root = self
                .precompile_witnesses
                .iter()
                .map(PrecompileWitness::root_unchecked)
                .reduce(fold_deferred_root)
                .expect("settlement requires at least one witness");
            if requested_root != available_root {
                return Err(SettlementEventError::RootMismatch {
                    requested: requested_root,
                    available: available_root,
                }
                .into());
            }

            let proof_key = proof_request_key(verifier_root, requested_root);
            if process.advice_provider().map().get(&proof_key).is_some() {
                return Err(SettlementEventError::PackageAlreadyLoaded.into());
            }

            // This host yields once, then proves locally. A host using a remote prover could
            // await its response here.
            tokio::task::yield_now().await;
            let precompile_proof = Prover::new()
                .with_hash_fn(HashFunction::Poseidon2)
                .prove_precompiles(self.precompile_witnesses.clone())
                .map_err(SettlementEventError::Proving)?;
            // Package the proof under the request key. MASM fetches it when request_proof returns.
            let package = PvmRecursiveVerifierInputs::for_request(verifier_root, &precompile_proof)
                .map_err(SettlementEventError::Advice)?;
            let (advice, _) = package.into_parts();
            let (_, advice_map, store) = advice.into_parts();
            let merkle_nodes = store.inner_nodes();
            self.precompile_proof = Some(precompile_proof);

            Ok(vec![
                AdviceMutation::extend_map(advice_map),
                AdviceMutation::extend_merkle_store(merkle_nodes),
            ])
        }
    }
}

#[derive(Debug, thiserror::Error)]
enum SettlementEventError {
    #[error("requested verifier root {requested:?} does not match expected root {expected:?}")]
    VerifierRootMismatch { requested: Word, expected: Word },
    #[error("requested deferred root {requested:?} does not match available root {available:?}")]
    RootMismatch { requested: Word, available: Word },
    #[error("a PVM proof package was already loaded before the settlement event")]
    PackageAlreadyLoaded,
    #[error("PVM proof generation failed: {0}")]
    Proving(#[source] ProverError),
    #[error("PVM recursive-verifier advice construction failed: {0}")]
    Advice(#[source] PvmRecursiveVerifierInputsError),
}
